"use client"
import type { Metadata } from "next";

import "./globals.css";

import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";


import { CartProvider } from "@/context/CartContext";

// Import GSAP
import { gsap } from "gsap";
import Layout from "@/components/Layout";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Cart from "@/components/Cart";

// Initialize GSAP plugins if needed
// gsap.registerPlugin(ScrollTrigger);

const queryClient = new QueryClient();
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
       <QueryClientProvider client={queryClient}>
       <Toaster />
       <Sonner position="top-center" />
       <TooltipProvider>
       <CartProvider>
       <Navbar />
       <Cart />
       {/* <Cart /> */}
      {children}
      <Footer/>
      </CartProvider>
      </TooltipProvider>
    </QueryClientProvider>
      </body>
    </html>
  );
}
